### ISSUE TITLE
Add META.json

### ISSUE THREAD

**Issue by JJ** [edsu/www-wikipedia#8]
Add this file which is actually auto-generated somewhere.

**Comment by bricas** [comment]
Thanks for the suggestion, but I don't think auto-generated files should be in the repo. The "standard" perl-github .gitignore file has META.json in the list:

https://github.com/github/gitignore/blob/master/Perl.gitignore

**Comment by JJ** [comment]
Actualli, this was specifically requested when this package was assigned to me:
![screenshot from 2017-07-28 18 04 30](https://user-images.githubusercontent.com/500/28725910-52ac567a-73bf-11e7-998f-765c5c591c4d.png)
Actually, @neilb has been pushing towards using either META.json or META.yml in modules, I tend to go along with him. But I can erase that if you want.

**Comment by bricas** [comment]
I I don't think the instructions mean adding it to the repo, per-se, but having the build process do it -- it currently only generates a META.yml file.

Sidebar: the module currently uses Module::Install which is problematic with the @INC change in Perl 5.26 -- switching it to something else might give us the added benefit of auto-generating a META.json file.

**Comment by JJ** [comment]
OK, I removed that in the last commit.
